# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-3.4.4
# Modified to include prediction endpoint container
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-02-13T21:02:17Z"
  labels:
    app: 3C-SCSU-pod
  name: 3C-SCSU-pod
spec:
  containers:
    - args:
        - start-notebook.sh
      image: docker.io/jdknuds/jupyter_pyten:latest
      name: pytenjup-pod
      ports:
        - containerPort: 8888
          hostPort: 10000
        - containerPort: 80
          hostPort: 9000
      resources: {}
      securityContext:
        capabilities:
          drop:
            - CAP_MKNOD
            - CAP_NET_RAW
            - CAP_AUDIT_WRITE
      volumeMounts:
        - mountPath: /home/jovyan/data
          name: data
        - mountPath: /home/jovyan/notebooks
          name: notebook-pvc
    - args:
        - nginx
        - -g
        - daemon off;
        - -c
        - /etc/nginx/nginx.conf
      image: docker.io/library/nginx:latest
      name: nginx-pod
      ports:
        - containerPort: 80
      resources: {}
      securityContext:
        capabilities:
          drop:
            - CAP_MKNOD
            - CAP_NET_RAW
            - CAP_AUDIT_WRITE
      volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-config
          subPath: nginx.conf
    - image: docker.io/jdknuds/prediction:latest
      name: prediction-pod
      command: ["gunicorn"]
      args: ["--bind", "0.0.0.0:5000", "--workers", "2", "server.server:app"]
      ports:
        - containerPort: 5000
      resources: {}
      securityContext:
        capabilities:
          drop:
            - CAP_MKNOD
            - CAP_NET_RAW
            - CAP_AUDIT_WRITE
    - image: docker.io/library/rust:latest
      name: rust-pod
      resources: {}
      securityContext:
        capabilities:
          drop:
            - CAP_MKNOD
            - CAP_NET_RAW
            - CAP_AUDIT_WRITE
  restartPolicy: Always
  volumes:
    - hostPath:
        path: ./data
        type: Directory
      name: data
    - name: notebook-pvc
      persistentVolumeClaim:
        claimName: notebook-pvc
    - name: nginx-config
      configMap:
        name: nginx-config
status: {}
